apiVersion: v1
kind: Service
metadata:
  name: {{ include "ambassador-agent.fullname" . }}
  namespace: {{ include "ambassador-agent.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "ambassador-agent.name" . }}
    {{- include "ambassador-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    {{- include "ambassador-agent.selectorLabels" . | nindent 4 }}
